@startuml

Title Olsker Cupcakes

state index.jsp
state CreateUser.jsp
state userPage.jsp
state LogPå

[*] --> index.jsp
index.jsp --> LogPå: Log på
LogPå --> index.jsp: Log på [fejl]
LogPå --> userPage.jsp: Log på [ok] (HelloServlet)
index.jsp --> CreateUser.jsp: Opret bruger (ServletCreateUser)
CreateUser.jsp --> userPage.jsp: Opret bruger [ok] (HelloServlet)
userPage.jsp --> LoggedOn

state LoggedOn {
    state adminPage.jsp
    state CurrentOrders.jsp
    state CupcakeMaker.jsp
    state Checkout.jsp
    state Payment.jsp

    [*] --> adminPage.jsp
    adminPage.jsp --> CurrentOrders.jsp: se ordrer (ServletOversigt)
    [*] --> CupcakeMaker.jsp: lav cupcakes (ServletCake)
    CupcakeMaker.jsp --> Checkout.jsp: læg cupcakes i kurven (ServletCheckout)
    Checkout.jsp --> Payment.jsp: betal for cupcakes (ServletPay)



}


@enduml